---
title: "trash_can"
author: "Lucia Martinez Rodriguez"
date: "`r Sys.Date()`"
output: html_document
---

## Packages installation

```{r}
library(dplyr)
```

## RNASeq BC's Data download from CPTAC

```{r, eval = FALSE}

# Código de descarga de datos desde TCGAbiolinks.

BiocManager::install("TCGAbiolinks")
library(TCGAbiolinks)

query <- GDCquery(project = 'CPTAC-2',
                  data.category = "Transcriptome Profiling",
                  data.type = "Gene Expression Quantification",
                  experimental.strategy = "RNA-Seq",
                  workflow.type = "STAR - Counts"
                  )

GDCdownload(query, method = "api") # Descarga de los datos por API

data <- GDCprepare(query) # Convierte los datos descargados en un formato listo para análisis, compatible con R

# saveRDS(data, file = "ruta/nombre.rds") 

# Este paso me da error. 

mrna = assay(data) #`assay(data)` devuelve una matriz donde las filas corresponden a genes y las columnas a muestras.

meta = colData(data)

data.conteos <- as.data.frame(t(mrna)) # Transponen la matriz para que queden muestras en filas y genes en columnas.

```